import { NextRequest, NextResponse } from 'next/server'
import { GoogleGenerativeAI } from '@google/generative-ai'

export async function POST(req: Request) {
    try {
        const { prompt: treatmentStep, type, diagnosis, leafBase64, language = 'en' } = await req.json();
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) return NextResponse.json({ success: false, error: 'API key missing' });

        const genAI = new GoogleGenerativeAI(apiKey);
        const languageName = language === 'ar' ? 'Arabic' : language === 'fr' ? 'French' : 'English';

        // 1. Try Gemini 3 Pro Image Preview (Image Mode)
        try {
            const model = genAI.getGenerativeModel({
                model: 'gemini-3-pro-image-preview',
                generationConfig: { temperature: 0.15 }
            });

            const imgPrompt = `
              GENERATE IMAGE REQUEST:
              Create a stunning, professional 4K horizontal tutorial diagram: "How to ${treatmentStep}" ${diagnosis ? `for ${diagnosis}` : ''}.
              Aspect Ratio: 3:1 (Horizontal Strip).
              STYLE: High-fidelity minimalist vector art with photo-realistic plant textures.
              LANGUAGE: Any text in the image (titles, labels) MUST be in ${languageName}.
            `;
            const content: any[] = [imgPrompt];
            if (leafBase64) content.push({ inlineData: { data: leafBase64, mimeType: 'image/jpeg' } });

            const result = await model.generateContent(content);
            // @ts-ignore
            const candidates = result?.response?.candidates;
            // @ts-ignore
            const imgData = candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;

            if (imgData) {
                return NextResponse.json({
                    success: true,
                    data: `data:image/png;base64,${imgData}`,
                    attribution: "Generated by Gemini 3 Pro Image (Nano Banana Pro)"
                });
            }
        } catch (e) {
            console.warn("Nano Banana Pro Image Mode failed, falling back to SVG:", e);
        }

        // 2. Fallback: Gemini 3 Pro Preview (SVG Mode)
        // High-quality multimodal generation.
        const model = genAI.getGenerativeModel({
            model: 'gemini-3-pro-preview',
            generationConfig: { temperature: 0.2 }
        });

        const svgPrompt = `
      You are an Expert Technical Illustrator (Nano Banana Pro Engine).
      
      REQUEST: Create a PROFESSIONAL 3-PANEL SVG TUTORIAL STRIP for: "${treatmentStep}" ${diagnosis ? `(Context: ${diagnosis})` : ''}.
      LANGUAGE: All text labels in the SVG MUST be in ${languageName}.
      
      STYLE & LAYOUT:
      - Use a horizontal layout (viewBox="0 0 1200 400").
      - Background: #FAF3E6 (Cream/Paper).
      - Panels: 3 distinct rounded rectangles with borders.
      - Colors: #2D4F37 (Forest Green), #EAB308 (Warning), #F97316 (Action).
      - Content: 
        1. Identification (Zoom on leaf/problem).
        2. Action (Tool/Spray/Hand).
        3. Result (Clean/Disposed).
      - Add Arrows between panels.
      - Add concise Text Labels inside.
      - Ensure the SVG is responsive and fully valid XML.
      
      OUTPUT: Return ONLY raw <svg>...</svg> code. No markdown or backticks.
    `;

        const content: any[] = [svgPrompt];
        if (leafBase64) {
            content.push({ inlineData: { data: leafBase64, mimeType: 'image/jpeg' } });
        }

        try {
            const result = await model.generateContent(content);
            const text = result.response.text();
            const cleanedSvg = text.replace(/```(xml|svg)?/g, '').replace(/```/g, '').trim();

            // Basic validation
            if (!cleanedSvg.startsWith('<svg') && !cleanedSvg.includes('<svg')) {
                throw new Error('No SVG generated');
            }

            return NextResponse.json({
                success: true,
                data: cleanedSvg,
                attribution: "Generated by Gemini 1.5 Flash (Nano Banana Pro)"
            });
        } catch (e: any) {
            console.error('Gemini generation failed:', e);
            return NextResponse.json({
                success: false,
                error: 'Failed to generate visual',
                details: e.message
            }, { status: 500 });
        }
    } catch (error: any) {
        console.error('Outer API error:', error);
        return NextResponse.json({ success: false, error: 'Server fatal error' }, { status: 500 });
    }
}
